apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jsonplaceholder
  labels:
    app: {{ .Release.Name }}-deploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name  : {{ .Release.Name }}-container
          image : {{ .Values.container.image }}
          resources:
            limits:
              memory : {{ .Values.resources.memory }}
              cpu    : {{ .Values.resources.cpu }}
          ports:
            - containerPort: {{ .Values.container.container_port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.container_port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.container_port }}
            initialDelaySeconds: 10
            periodSeconds: 20
