apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jsonplaceholder
  labels:
    app: {{ .Release.Name }}-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name  : {{ .Release.Name }}-container
          image : {{ .Values.container.image }}
          resources:
            limits:
              memory : {{ .Values.resources.memory }}
              cpu    : {{ .Values.resources.cpu }}
          ports:
            - containerPort: {{ .Values.container.container_port }}

